const express =require('express')
const mongoose =require('mongoose')
const cors=require('cors')
const app =express()
app.use(cors())
app.use(express.json())
app.use(express.urlencoded())
app.use('/login',require('./loginprec'))
app.use('/refister',require('./registerrecip'))
app.use('/posts',require('./createing'))
app.listen(3000,async()=>{
    await mongoose.connect('mongodb+srv://Aro:aro123@arockiajeyson.aswzaya.mongodb.net/?retryWrites=true&w=majority')
    console.log('db connected')
    console.log('port up')
})